### ISSUE TITLE
Tags are not showing

### ISSUE THREAD

**Issue by carlosgasa** [bitbrain/jekyll-dash#19]
Hi, I'm newbie in the Jekyll. I forked the project (https://github.com/carlosgasa/jekyll-dash) and send to Github pages without make changes, so the problem is that the tags are not showing, you can see the page in the https://carlosgasa.github.io/jekyll-dash
Any response about this?

**Comment by bitbrain** [comment]
Hey @carlosgasa - this is not a bug but rather [a limitation by Github pages](https://pages.github.com/versions/) when using the Jekyll generator on Github. In order to generate tags and pages, the [jekyll-tagging](https://github.com/bitbrain/jekyll-dash/blob/master/Gemfile#L4) plugin is used. If you want to have tags to show up, you need to [generate your page via TravisCI](https://github.com/bitbrain/blog/blob/master/.travis.yml). To achieve that, you require 2 repositories:

* carlosgasa/blog (contains the actual markdown sources and Jekyll code)
* carlosgasa/carlosgasa.github.io (this repository hosts the generated files, pushed by Travis)

You need the following workflow to use custom plugins on Github pages:

1. TravisCI builds your `blog` project
2. TravisCI pushes your `_site` contents to `carlosgasa/carlosgasa.github.io`

I will extend the `README.md` to make this clear, thanks for reporting this since it is not obvious for people who just start out with Jekyll!

**Comment by bitbrain** [comment]
Updated README https://github.com/bitbrain/jekyll-dash#using-this-theme-directly-on-github-pages
