### ISSUE TITLE
How to display post tags?

### ISSUE THREAD

**Issue by kodumulo** [bitbrain/jekyll-dash#45]
i fork your jekyll-dash and i see my blog
when i can't see my post tags in mainpage
what the problem?
<img width="335" alt="스크린샷 2020-08-13 오전 1 36 17" src="https://user-images.githubusercontent.com/60311485/90042885-3fe90700-dd06-11ea-94a1-9c4843c18668.png">
this is my post code 
<img width="325" alt="스크린샷 2020-08-13 오전 1 36 28" src="https://user-images.githubusercontent.com/60311485/90042967-5b541200-dd06-11ea-8e08-e10cfd24489a.png">
and this is my blog site
<img width="83" alt="스크린샷 2020-08-13 오전 1 37 23" src="https://user-images.githubusercontent.com/60311485/90042996-660ea700-dd06-11ea-82df-f93a6450d1cd.png">
this is your blog
how can i fix this problem?
thanks

**Comment by bitbrain** [comment]
Hello @kodumulo!

After looking at your setup I might have a suspicion what may cause the problem. First of all, let me make sure that I understand correctly:

- you cloned the jekyll-dash sources to https://github.com/kodumulo/kodumulo.github.io
- additionally, you created https://github.com/kodumulo/blog/blob/master/.travis.yml however that does not seem to do anything (yet) because it does not contain any files

As far as I can tell, [your blog is being built via the Github Actions](https://github.com/kodumulo/kodumulo.github.io/runs/979309730) rather than with your own action. This will not work [as stated in the jekyll-dash README](https://github.com/bitbrain/jekyll-dash#faq):

> Solution: as described above you have to add the tagging plugin. Additionally, tags do not work natively by Github Pages. You have to build your site on an external CI and push the _site artifacts to a hosting repository.

Unfortunately, this is due to a limitation of the Github Pages feature that only allows a limited set of gems.

So, what you actually have to do, is move all the contents of your https://github.com/kodumulo/kodumulo.github.io to your https://github.com/kodumulo/blog repository. You should never commit/touch https://github.com/kodumulo/kodumulo.github.io yourself. Instead, use the Github action you already setup in your blog repository to push HTML/CSS files into https://github.com/kodumulo/kodumulo.github.io. Github then will just use the generated files for your website.

Let me know if you face any more issues!

**Comment by bitbrain** [comment]
@kodumulo glad I could help! Please raise another issue if you encounter any further problems.

**Comment by Xan0er** [comment]
I am not ableto figure out how to build site externally and all these steps that you mentioned. Can you please help me?
